[log]
# 忽略level以下不包括level的日志
level = 'DEFAULT'

AsyncLogger.flush_val = 3
AsyncLogger.buffer_vector_size = 8
AsyncLogger.buffer_vector_free_size = 4
AsyncLogger.buffer_to_write_max = 16

LogFile.output_path = "log/tsuki.log"

# 历史log归档信息(自动)
logHistoryRecordPath = "log/logHistoryRecord.txt"